// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Loads `.env.local` (Next.js convention) so a single env file works for
// both `next dev` and the Prisma CLI (e.g. `prisma migrate`).
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Explicit, pre-created shadow DB (used by `migrate dev` to diff
    // schema changes) instead of letting Prisma auto-create/drop one via
    // Postgres's implicit `template1` default template.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
